version: '3.1'

services:

  db:
    image: mysql:8.3
    container_name: youth-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: youth
    ports:
      - "3307:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youth-app-container
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql-data:
