spring:

  # Database - 추후에 환경변수 설정 필요
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}

  # Spring Data JPA
  jpa:
    show-sql: 'false'
    hibernate:
      ddl-auto: create
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.MySQLDialect

  # JWT 설정
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    token-validity: ${JWT_TOKEN_VALIDITY}

# p6spy log
decorator:
  datasource:
    p6spy:
      enable-logging: 'true'

# logging
logging:
  level:
    org:
      springframework:
        core:
          LocalVariableTableParameterNameDiscoverer: error
      hibernate:
        sql: debug
    p6spy: info