spring:

  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://52.79.103.61:3307/youth

  # Spring Data JPA
  jpa:
    show-sql: 'false'
    hibernate:
      ddl-auto: create
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.MySQLDialect

# p6spy log
decorator:
  datasource:
    p6spy:
      enable-logging: 'true'

# logging
logging:
  level:
    org:
      springframework:
        core:
          LocalVariableTableParameterNameDiscoverer: error
      hibernate:
        sql: debug
    p6spy: info