spring:

  # Database - 추후에 환경변수 설정 필요
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fmhj
    password: dbtmrkalfoek!!
    url: jdbc:mysql://52.79.103.61:3306/youth

  # Spring Data JPA
  jpa:
    show-sql: 'false'
    hibernate:
      ddl-auto: create
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.MySQLDialect

  # JWT 설정
  jwt:
    secret-key: VlwEyVBsYt9V7zq57TejMnTUyz5lYcfPQye08f7MhQA9XkHa
    token-validity: 86400000

# p6spy log
decorator:
  datasource:
    p6spy:
      enable-logging: 'true'

# logging
logging:
  level:
    org:
      springframework:
        core:
          LocalVariableTableParameterNameDiscoverer: error
      hibernate:
        sql: debug
    p6spy: info